trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Maven project'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - script: |
              sudo apt-get update
              sudo apt-get install -y openjdk-11-jdk  # Install the desired Java version
              echo "JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 | grep 'java.home' | awk '{print $3}')" | sudo tee /etc/environment
              echo "PATH=$JAVA_HOME/bin:$PATH" | sudo tee -a /etc/environment
              source /etc/environment
              java -version  # Verify Java version
              mvn clean package
            displayName: 'Build with Maven'

  - stage: DockerBuild
    displayName: 'Build Docker image'
    dependsOn: Build
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              containerRegistry: 'Docker Registry'  # Replace with your Docker Hub connection name
              repository: 'thatsha/selenium-project'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: 'latest'
