trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Maven project'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: UseJavaVersion@1
            inputs:
              versionSpec: '11'
              addToPath: true

          - script: 'mvn clean package'
            displayName: 'Build with Maven'

  - stage: DockerBuild
    displayName: 'Build Docker image'
    dependsOn: Build
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: Docker@2
            displayName: 'Build Docker image'
            inputs:
              containerRegistry: 'thatsha'  # Replace with your Docker Hub connection name
              repository: 'yourdockerhubusername/selenium-project'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: 'latest'

  - stage: PushToDockerHub
    displayName: 'Push Docker image to Docker Hub'
    dependsOn: DockerBuild
    jobs:
      - job: Push
        displayName: 'Push'
        steps:
          - task: Docker@2
            displayName: 'Push Docker image'
            inputs:
              containerRegistry: 'thatsha'  # Replace with your Docker Hub connection name
              repository: 'yourdockerhubusername/selenium-project'
              command: 'push'
              tags: 'latest'
